Transcription errors
standardebooks/j-sheridan-le-fanu_uncle-silas pull request #5
Opened 2024-04-18 11:37 UTC by chapkachapka

I noted a few errors in this text while reading. Checked all against the listed image source and corrected. I also added language semantics for a word not in M-W, "Aetate".

2024-04-18 16:49 UTC, acabal requested changes

2024-04-18 16:49 UTC, acabal commented on src/epub/text/chapter-1-22.xhtml
> +			<p>It ended by our peeping out, all three in a body, upon the gallery. Through each window in the perspective came its blue sheet of moonshine; but the door on which our attention was fixed was in
It looks like you introduced a typo here, `hee`. Can you fix that?

2024-04-19 13:31 UTC, chapkachapka commented
I think I fixed that and pushed it out correctly--let me know if there's something else I need to do.

2024-04-19 16:11 UTC, merged

2024-04-19 16:11 UTC, acabal commented
Thanks!